version: '3.9'
services:
  db:
    image: mysql:8.0.35-debian
    container_name: smvc-primer_db
    ports: 
      - "23306:3306"
    environment:
        MYSQL_DATABASE: smvcbase_in_docker
        MYSQL_USER: myuser
        MYSQL_PASSWORD: 12345
        MYSQL_ROOT_PASSWORD: 12345
    volumes:
        - ../dump:~
    networks:
        - default